### ISSUE TITLE
1. remove redundant "sudo" 2. possible shell compatibility issue.

### ISSUE THREAD

**Issue by AlexScheller** [uncheckederror/UbuntuGISToolsSetup#1]
1. Instead of having multiple "sudo"s in the script "GISToolsAutoSetup.sh", you could just amend the readme to instruct users to run the entire script with elevated priviledges, i.e.

`sudo ./GISToolsAutoSetup.sh`

2. It seems that this script assumes that the working shell is bash (as opposed to zsh, fish, etc.), although this isn't reflected in the readme.

Also hi Tom.

**Comment by uncheckederror** [comment]
@AlexScheller thanks for the feedback!

I have removed the pile of sudos and amend the readme.

I have updated the readme to reflect that this is a BASH script.

Hey Alex!
